# ===============================================
# DOCKER COMPOSE - POSTGRESQL PARA IMDB SCRAPER
# ===============================================

version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: imdb_postgres_db
    environment:
      POSTGRES_DB: imdb_scraper_db
      POSTGRES_USER: imdb_user
      POSTGRES_PASSWORD: imdb_secure_2024
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ../database/initial_data.sql:/docker-entrypoint-initdb.d/02-initial_data.sql
    networks:
      - imdb_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U imdb_user -d imdb_scraper_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: imdb_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@imdb-scraper.local
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - imdb_network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  imdb_network:
    driver: bridge
